import { Yogasana, HealthCondition, Instructor, ResearchArticle, Testimonial, Challenge, BlogPost, ForumPost, Badge } from "./types";

export const translations: Record<string, Record<string, string>> = {
  en: {
    brand: "YogaVeda",
    subtitle: "Your Authentic Guide to Holistic Wellness",
    heroTitle: "Transform Your Mind, Body & Soul",
    heroSubtitle: "Practice authentic Yogasanas, meditation pathways, and science-grounded therapeutic wellness guides designed for your anatomy.",
    ctaStart: "Start Your Journey",
    ctaExplore: "Explore Yogasanas",
    categoriesTitle: "Targeted Yoga Categories",
    categoriesSub: "Curated programs for specific health objectives and experience levels.",
    popularTitle: "Popular Yogasanas",
    popularSub: "Master foundational yoga postures with scientific precision and step-by-step breathing.",
    learnMore: "Learn More",
    viewDetails: "View Details",
    whyChoose: "Why YogaVeda?",
    whyChooseSub: "Bridging the wisdom of traditional Hatha yoga with modern clinical studies.",
    healthTitle: "Yoga for Health Conditions",
    healthSub: "Select chronic conditions or lifestyle adjustments to discover dedicated, safe routines.",
    aiCoachTitle: "AI Yoga Recommendation Tool",
    aiCoachSub: "Unlock your personalized weekly schedule generated by our intelligent backend.",
    journeyTitle: "Your Yoga Learning Journey",
    journeySub: "A step-by-step roadmap to progress from fundamental breath awareness to spiritual mastery.",
    teachersTitle: "Sutra Expert Teachers",
    teachersSub: "Learn from teachers certified in therapeutic yoga, biomechanics, and Sanskrit wisdom.",
    videoLibrary: "Video Tutorials",
    videoSub: "Follow direct alignment video guidelines with safe, slow pacings.",
    scienceTitle: "Scientific & Clinical Research",
    scienceSub: "Peer-reviewed studies demonstrating the direct metabolic, mental, and physical impacts of Yoga.",
    testimonialsTitle: "Practitioner Journeys",
    testimonialsSub: "Stories of healing, strength, and inner stillness from our global community.",
    challengesTitle: "Mindful Yoga Challenges",
    challengesSub: "Build routines that last. Progress at your own pace and track daily milestones.",
    blogTitle: "Sutra Insights",
    blogSub: "Read about nutrition, posture mechanics, Ayurvedic guidance, and wellness schedules.",
    mobileApp: "YogaVeda Mobile App",
    mobileIntro: "Stay consistent with offline access, custom yoga audio tracks, and intuitive visual cues.",
    faqTitle: "Frequently Asked Questions",
    faqSub: "Common inquiries for beginners and advanced yogis answered safely.",
    poseFinder: "Yoga Pose Finder",
    poseFinderSub: "Filter by difficulty, muscle group, benefits, or direct keywords.",
    bmiTitle: "Sutra BMI Health Advisor",
    bmiSub: "Calculate your body mass index and get contextual daily yoga recommendations.",
    calorieTitle: "Yoga Calorie Burner",
    calorieSub: "Understand your energy expenditure across traditional holds.",
    trackerTitle: "Daily Habit & Sadhana Tracker",
    trackerSub: "Maintain consistency through conscious daily commitments.",
    timerTitle: "Sutra Meditation Timer",
    timerSub: "Rest your mind in custom silent holds with natural atmospheric cues.",
    forumTitle: "Yogic Community Forum",
    forumSub: "Share your achievements, ask posture alignments, and connect with global seekers.",
    badgesTitle: "Practitioner Badges & Ribbons",
    badgesSub: "Your achievements and consistency milestones visualized.",
    backToHome: "Back to Dashboard",
    difficultyLevel: "Difficulty Level",
    duration: "Hold Duration",
    benefits: "Therapeutic Benefits",
    precautions: "Precautions & Contraindications",
    commonMistakes: "Common Mistakes to Avoid",
    breathingPattern: "Breathing Coordinates",
    scientificResearch: "Scientific Evidence",
    relatedPoses: "Related Poses",
    avoidIf: "Avoid Practice If:",
    physicalBenefits: "Physical Benefits",
    mentalBenefits: "Mental Benefits",
    medicalBenefits: "Medical Impact",
    stepByStep: "Step-by-Step Instructions",
    inhale: "Inhale",
    exhale: "Exhale",
    hold: "Hold Breath",
    targetParts: "Target Anatomy",
    all: "All",
    beginner: "Beginner",
    intermediate: "Intermediate",
    advanced: "Advanced",
  },
  hi: {
    brand: "योगवेद",
    subtitle: "समग्र स्वास्थ्य के लिए आपका विश्वसनीय मार्गदर्शक",
    heroTitle: "मन, शरीर और आत्मा का रूपांतरण करें",
    heroSubtitle: "प्रामाणिक योगासन, ध्यान पथ और विज्ञान पर आधारित स्वास्थ्य गाइडों का अभ्यास करें।",
    ctaStart: "यात्रा शुरू करें",
    ctaExplore: "योगासन खोजें",
    categoriesTitle: "लक्षित योग श्रेणियां",
    categoriesSub: "विशिष्ट स्वास्थ्य लक्ष्यों और अनुभव स्तरों के लिए क्यूरेटेड कार्यक्रम।",
    popularTitle: "लोकप्रिय योगासन",
    popularSub: "वैज्ञानिक सटीकता और चरण-दर-चरण श्वास के साथ बुनियादी मुद्राओं में महारत हासिल करें।",
    learnMore: "अधिक जानें",
    viewDetails: "विवरण देखें",
    whyChoose: "योगवेद क्यों चुनें?",
    whyChooseSub: "पारंपरिक हठ योग के ज्ञान को आधुनिक नैदानिक अध्ययनों के साथ जोड़ना।",
    healthTitle: "स्वास्थ्य स्थितियों के लिए योग",
    healthSub: "समर्पित और सुरक्षित दिनचर्या की खोज के लिए पुरानी बीमारियों या जीवन शैली का चयन करें।",
    aiCoachTitle: "एआई योग अनुशंसा उपकरण",
    aiCoachSub: "हमारे बुद्धिमान बैकएंड द्वारा उत्पन्न अपनी व्यक्तिगत साप्ताहिक योजना प्राप्त करें।",
    journeyTitle: "आपकी योग सीखने की यात्रा",
    journeySub: "बुनियादी सांस जागरूकता से लेकर आध्यात्मिक महारत तक आगे बढ़ने का रोडमैप।",
    teachersTitle: "विशेषज्ञ योग शिक्षक",
    teachersSub: "चिकित्सीय योग, बायोमैकेनिक्स और संस्कृत ज्ञान में प्रमाणित शिक्षकों से सीखें।",
    videoLibrary: "वीडियो ट्यूटोरियल",
    videoSub: "सुरक्षित और धीमी गति के साथ प्रत्यक्ष संरेखण वीडियो दिशानिर्देशों का पालन करें।",
    scienceTitle: "वैज्ञानिक और नैदानिक शोध",
    scienceSub: "योग के प्रत्यक्ष चयापचय, मानसिक और शारीरिक प्रभावों को प्रदर्शित करने वाले शोध पत्र।",
    testimonialsTitle: "साधकों की यात्रा",
    testimonialsSub: "हमारे वैश्विक समुदाय से उपचार, शक्ति और आंतरिक शांति की कहानियां।",
    challengesTitle: "सचेतन योग चुनौतियां",
    challengesSub: "स्थायी दिनचर्या बनाएं। अपनी गति से प्रगति करें और दैनिक मील के पत्थर ट्रैक करें।",
    blogTitle: "योग अंतर्दृष्टि",
    blogSub: "पोषण, आसन यांत्रिकी, आयुर्वेदिक मार्गदर्शन और कल्याण योजनाओं के बारे में पढ़ें।",
    mobileApp: "योगवेद मोबाइल ऐप",
    mobileIntro: "ऑफ़लाइन पहुंच, कस्टम योग ऑडियो ट्रैक और सहज दृश्य संकेतों के साथ सुसंगत रहें।",
    faqTitle: "अक्सर पूछे जाने वाले प्रश्न",
    faqSub: "शुरुआती और उन्नत योगियों के सवालों के जवाब प्राप्त करें।",
    poseFinder: "योग मुद्रा खोजक",
    poseFinderSub: "कठिनाई, मांसपेशी समूह, लाभ, या खोज शब्दों द्वारा फ़िल्टर करें।",
    bmiTitle: "योगवेद बीएमआई स्वास्थ्य सलाहकार",
    bmiSub: "अपने बॉडी मास इंडेक्स की गणना करें और दैनिक योग अनुशंसाएं प्राप्त करें।",
    calorieTitle: "योग कैलोरी बर्नर",
    calorieSub: "पारंपरिक मुद्राओं में अपनी ऊर्जा व्यय को समझें।",
    trackerTitle: "दैनिक आदत और साधना ट्रैकर",
    trackerSub: "दैनिक प्रतिबद्धताओं के माध्यम से निरंतरता बनाए रखें।",
    timerTitle: "योगवेद ध्यान टाइमर",
    timerSub: "प्राकृतिक वायुमंडलीय संकेतों के साथ शांत ध्यान का अभ्यास करें।",
    forumTitle: "योग सामुदायिक मंच",
    forumSub: "अपनी उपलब्धियों को साझा करें, मुद्रा सुधार पूछें और वैश्विक खोजीों से जुड़ें।",
    badgesTitle: "साधक बैज और पुरस्कार",
    badgesSub: "आपकी निरंतरता और अनुशासन के मील के पत्थर।",
    backToHome: "डैशबोर्ड पर वापस",
    difficultyLevel: "कठिनाई स्तर",
    duration: "मुद्रा की अवधि",
    benefits: "चिकित्सीय लाभ",
    precautions: "सावधानियां",
    commonMistakes: "बचने योग्य सामान्य गलतियां",
    breathingPattern: "श्वास क्रियाविधि",
    scientificResearch: "वैज्ञानिक प्रमाण",
    relatedPoses: "संबंधित आसन",
    avoidIf: "इस स्थिति में अभ्यास न करें:",
    physicalBenefits: "शारीरिक लाभ",
    mentalBenefits: "मानसिक लाभ",
    medicalBenefits: "चिकित्सीय प्रभाव",
    stepByStep: "चरण-दर-चरण निर्देश",
    inhale: "सांस लें (Inhale)",
    exhale: "सांस छोड़ें (Exhale)",
    hold: "सांस रोकें (Hold)",
    targetParts: "लक्षित शरीर रचना",
    all: "सभी",
    beginner: "शुरुआती",
    intermediate: "मध्यम",
    advanced: "उन्नत",
  },
  mr: {
    brand: "योगवेद",
    subtitle: "समग्र कल्याणासाठी आपला विश्वसनीय मार्गदर्शक",
    heroTitle: "मन, शरीर आणि आत्म्याचे परिवर्तन करा",
    heroSubtitle: "अधिकृत योगासने, ध्यान पद्धती आणि विज्ञान-आधारित आरोग्य मार्गदर्शकांचा सराव करा.",
    ctaStart: "प्रवास सुरू करा",
    ctaExplore: "योगासने शोधा",
    categoriesTitle: "लक्षित योग श्रेणी",
    categoriesSub: "विशिष्ट आरोग्य उद्दिष्टे आणि अनुभव पातळीसाठी तयार केलेले कार्यक्रम.",
    popularTitle: "लोकप्रिय योगासने",
    popularSub: "वैज्ञानिक अचूकता आणि टप्प्याटप्प्याने घेतलेल्या श्वासासह मूलभूत मुद्रांवर प्रभुत्व मिळवा.",
    learnMore: "अधिक जाणून घ्या",
    viewDetails: "तपशील पहा",
    whyChoose: "योगवेद का निवडावे?",
    whyChooseSub: "पारंपारिक हठयोगाचे ज्ञान आधुनिक क्लिनिकल अभ्यासांशी जोडणे.",
    healthTitle: "विविध आजारांसाठी योग",
    healthSub: "सुरक्षित आणि समर्पित योगासनांसाठी तुमची जीवनशैली किंवा आरोग्य स्थिती निवडा.",
    aiCoachTitle: "एआय योग शिफारस साधन",
    aiCoachSub: "आमच्या बुद्धिमान सिस्टीमद्वारे तयार केलेले वैयक्तिक साप्ताहिक वेळापत्रक मिळवा.",
    journeyTitle: "तुमचा योग शिकण्याचा प्रवास",
    journeySub: "मूलभूत श्वास जागरूकतेपासून ते आध्यात्मिक प्रभुत्वापर्यंत प्रगती करण्याचा मार्ग.",
    teachersTitle: "तज्ञ योग शिक्षक",
    teachersSub: "उपचारात्मक योग, बायोमेकॅनिक्स आणि संस्कृत ज्ञानातील प्रमाणित शिक्षकांकडून शिका.",
    videoLibrary: "व्हिडिओ मार्गदर्शक",
    videoSub: "सुरक्षित आणि संथ गतीने चालणाऱ्या थेट संरेखन व्हिडिओ मार्गदर्शकांचे अनुसरण करा.",
    scienceTitle: "वैज्ञानिक आणि नैदानिक संशोधन",
    scienceSub: "योगाचे थेट चयापचय, मानसिक आणि शारीरिक प्रभाव दर्शविणारे संशोधन पत्रक.",
    testimonialsTitle: "साधकांचे अनुभव",
    testimonialsSub: "आमच्या जागतिक समुदायाकडील बरे होण्याच्या, सामर्थ्याच्या आणि शांततेच्या कथा.",
    challengesTitle: "योग आव्हाने",
    challengesSub: "शाश्वत दिनचर्या तयार करा. स्वतःच्या गतीने प्रगती करा आणि दररोज मैलाचे दगड ट्रॅक करा.",
    blogTitle: "योगाविषयी सखोल ज्ञान",
    blogSub: "पोषण, मुद्रा यांत्रिकी, आयुर्वेदिक मार्गदर्शन आणि कल्याणाच्या वेळापत्रकांबद्दल वाचा.",
    mobileApp: "योगवेद मोबाईल ॲप",
    mobileIntro: "ऑफलाईन प्रवेश, सानुकूल योग ऑडिओ ट्रॅक आणि अंतर्ज्ञानी दृश्यांसह सुसंगत राहा.",
    faqTitle: "वारंवार विचारले जाणारे प्रश्न",
    faqSub: "सुरुवातीच्या आणि प्रगत योग्यांच्या प्रश्नांची सुरक्षितपणे उत्तरे दिलेली आहेत.",
    poseFinder: "योगासन शोधक",
    poseFinderSub: "पातळी, स्नायू गट, फायदे किंवा शोधशब्दांद्वारे फिल्टर करा.",
    bmiTitle: "योगवेद बीएमआय आरोग्य सल्लागार",
    bmiSub: "तुमच्या बॉडी मास इंडेक्सची गणना करा आणि दैनिक योग शिफारसी मिळवा.",
    calorieTitle: "योग कॅलरी बर्नर",
    calorieSub: "पारंपारिक आसनांमध्ये तुमची बर्न झालेली कॅलरी समजून घ्या.",
    trackerTitle: "दैनिक सवय आणि साधना ट्रॅकर",
    trackerSub: "दैनिक जागरूक वचनबद्धतेद्वारे सुसंगतता राखा.",
    timerTitle: "योगवेद ध्यान टाइमर",
    timerSub: "नैसर्गिक ध्वनी आणि संगीतासह ध्यानधारणा करा.",
    forumTitle: "योग सामुदायिक मंच",
    forumSub: "तुमची यशोगाथा सामायिक करा, मुद्रा सुधारणा विचारा आणि जागतिक साधकांशी जोडा.",
    badgesTitle: "साधक बॅजेस व पुरस्कार",
    badgesSub: "तुमचा नियमित सराव दर्शवणारे मैलाचे दगड.",
    backToHome: "डॅशबोर्डवर परत जा",
    difficultyLevel: "त्रास पातळी",
    duration: "मुद्रेचा कालावधी",
    benefits: "उपचारात्मक फायदे",
    precautions: "सावधगिरीचे उपाय",
    commonMistakes: "टाळावयाच्या सामान्य चुका",
    breathingPattern: "श्वसन क्रिया पद्धती",
    scientificResearch: "वैज्ञानिक पुरावा",
    relatedPoses: "संबंधित आसने",
    avoidIf: "या परिस्थितीत सराव टाळा:",
    physicalBenefits: "शारीरिक फायदे",
    mentalBenefits: "मानसिक फायदे",
    medicalBenefits: "वैद्यकीय परिणाम",
    stepByStep: "तपशीलवार मार्गदर्शक",
    inhale: "श्वास घ्या (Inhale)",
    exhale: "श्वास सोडा (Exhale)",
    hold: "श्वास रोखा (Hold)",
    targetParts: "लक्षित शरीर रचना",
    all: "सर्व",
    beginner: "शुरुवातीचे",
    intermediate: "मध्यम",
    advanced: "प्रगत",
  },
  gu: {
    brand: "યોગવેદ",
    subtitle: "સમગ્ર કલ્યાણ માટે તમારું વિશ્વસનીય માર્ગદર્શક",
    heroTitle: "મન, શરીર અને આત્માનું રૂપાંતરણ કરો",
    heroSubtitle: "અધિકૃત યોગાસન, ધ્યાન પદ્ધતિ અને વિજ્ઞાન-આધારિત આરોગ્ય માર્ગદર્શિકાઓનો અભ્યાસ કરો.",
    ctaStart: "યાત્રા શરૂ કરો",
    ctaExplore: "યોગાસનો શોધો",
    categoriesTitle: "લક્ષિત યોગ શ્રેણીઓ",
    categoriesSub: "ચોક્કસ આરોગ્ય લક્ષ્યો અને અનુભવ સ્તરો માટે ક્યુરેટેડ કાર્યક્રમો.",
    popularTitle: "લોકપ્રિય યોગાસનો",
    popularSub: "વૈજ્ઞાનિક ચોકસાઈ અને પગલા-દર-પગલા શ્વાસ સાથે મૂળભૂત મુદ્રાઓમાં નિપુણતા મેળવો.",
    learnMore: "આગળ વાંચો",
    viewDetails: "વિગત જુઓ",
    whyChoose: "યોગવેદ શા માટે પસંદ કરવું?",
    whyChooseSub: "પરંપરાગત હઠયોગના જ્ઞાનને આધુનિક ક્લિનિકલ અભ્યાસો સાથે જોડવું.",
    healthTitle: "આરોગ્યની સ્થિતિઓ માટે યોગ",
    healthSub: "સમર્પિત અને સુરક્ષિત દિનચર્યા શોધવા માટે ક્રોનિક રોગો અથવા જીવનશૈલી પસંદ કરો.",
    aiCoachTitle: "AI યોગ ભલામણ સાધન",
    aiCoachSub: "અમારી બુદ્ધિશાળી સિસ્ટમ દ્વારા જનરેટ કરાયેલ તમારો વ્યક્તિગત સાપ્તાહિક સમયપત્રક મેળવો.",
    journeyTitle: "તમારી યોગ શીખવાની યાત્રા",
    journeySub: "મૂળભૂત શ્વાસ જાગૃતિથી લઈને આધ્યાત્મિક નિપુણતા સુધી પ્રગતિ કરવાનો રોડમેપ.",
    teachersTitle: "નિષ્ણાત યોગ શિક્ષકો",
    teachersSub: "રોગનિવારક યોગ, બાયોમેકેનિક્સ અને સંસ્કૃત જ્ઞાનમાં પ્રમાણિત શિક્ષકો પાસેથી શીખો.",
    videoLibrary: "વિડિઓ માર્ગદર્શિકા",
    videoSub: "સુરક્ષિત અને ધીમી ગતિ સાથે સીધા વિડિઓ માર્ગદર્શનનું પાલન કરો.",
    scienceTitle: "વૈજ્ઞાનિક અને ક્લિનિકલ સંશોધન",
    scienceSub: "યોગની સીધી ચયાપચય, માનસિક અને શારીરિક અસરો દર્શાવતા સંશોધન પત્રો.",
    testimonialsTitle: "સાધકોની સફર",
    testimonialsSub: "અમારા વૈશ્વિક સમુદાય તરફથી સાજા થવાની, શક્તિ અને શાંતિની વાર્તાઓ.",
    challengesTitle: "યોગ પડકારો",
    challengesSub: "ટકાઉ દિનચર્યા બનાવો. તમારી પોતાની ગતિએ પ્રગતિ કરો અને દૈનિક માઇલસ્ટોન્સ ટ્રેક કરો.",
    blogTitle: "યોગ વિશે ઊંડાણપૂર્વક જ્ઞાન",
    blogSub: "પોષણ, આસન મિકેનિક્સ, આયુર્વેદિક માર્ગદર્શન અને કલ્યાણ સમયપત્રક વિશે વાંચો.",
    mobileApp: "યોગવેદ મોબાઇલ એપ",
    mobileIntro: "ઓફલાઇન એક્સેસ, કસ્ટમ યોગ ઓડિયો ટ્રેક અને સાહજિક સંકેતો સાથે સુસંગત રહો.",
    faqTitle: "વારંવાર પૂછાતા પ્રશ્નો",
    faqSub: "શરૂઆતી અને અદ્યતન યોગીઓના પ્રશ્નોના સુરક્ષિત રીતે જવાબો આપેલા છે.",
    poseFinder: "યોગાસન શોધક",
    poseFinderSub: "કઠિનતા સ્તર, સ્નાયુ જૂથ, ફાયદા અથવા શોધ શબ્દો દ્વારા ફિલ્ટર કરો.",
    bmiTitle: "યોગવેદ BMI હેલ્થ એડવાઇઝર",
    bmiSub: "તમારા બોડી માસ ઇન્ડેક્સની ગણતરી કરો અને દૈનિક યોગ ભલામણો મેળવો.",
    calorieTitle: "યોગ કેલરી બર્નર",
    calorieSub: "પરંપરાગત આસનોમાં તમારી ખર્ચ થયેલી કેલરીને સમજો.",
    trackerTitle: "દૈનિક આદત અને સાધના ટ્રેકર",
    trackerSub: "દૈનિક જાગૃત પ્રતિબદ્ધતાઓ દ્વારા સુસંગતતા જાળવો.",
    timerTitle: "યોગવેદ ધ્યાન ટાઈમર",
    timerSub: "કુદરતી અવાજો અને સંગીત સાથે ધ્યાન ધરો.",
    forumTitle: "યોગ પબ્લિક ફોરમ",
    forumSub: "તમારી સિદ્ધિઓ શેર કરો, મુદ્રા સંરેખણ પૂછો અને વૈશ્વિક અનિમેષકો સાથે જોડાઓ.",
    badgesTitle: "સાધક બેજ અને એવોર્ડ્સ",
    badgesSub: "તમારી સુસંગતતા દર્શાવતા મહત્વના સીમાચિહ્નો.",
    backToHome: "ડેશબોર્ડ પર પાછા ફરો",
    difficultyLevel: "મુશ્કેલી સ્તર",
    duration: "સ્થિતિ સમયગાળો",
    benefits: "ઉપચારાત્મક ફાયદાઓ",
    precautions: "સાવચેતીના પગલાં",
    commonMistakes: "ટાળવા જેવી સામાન્ય ભૂલો",
    breathingPattern: "શ્વાસ લેવાની રીત",
    scientificResearch: "વૈજ્ઞાનિક પુરાવા",
    relatedPoses: "સંબંધિત આસનો",
    avoidIf: "આ સ્થિતિમાં પ્રેક્ટિસ ટાળો:",
    physicalBenefits: "શારીરિક ફાયદાઓ",
    mentalBenefits: "માનસિક ફાયદાઓ",
    medicalBenefits: "તબીબી અસરો",
    stepByStep: "વિગતવાર માર્ગદર્શિકા",
    inhale: "શ્વાસ લો (Inhale)",
    exhale: "શ્વાસ છોડો (Exhale)",
    hold: "શ્વાસ રોકો (Hold)",
    targetParts: "લક્ષિત શરીર રચના",
    all: "બધા",
    beginner: "શરૂઆત કરનાર",
    intermediate: "મધ્યમ",
    advanced: "અદ્યતન",
  }
};

export const yogasanasData: Yogasana[] = [
  {
    id: "surya-namaskar",
    name: "Surya Namaskar",
    sanskritName: "सूर्यनमस्कार",
    englishName: "Sun Salutation",
    difficulty: "Intermediate",
    duration: "5 - 15 minutes (6-12 rounds)",
    category: "Weight Loss Yoga",
    benefits: {
      physical: ["Stretches and strengthens entire musculoskeletal system", "Improves joints flexibility", "Enhances spinal flexibility", "Stimulates major muscle groups"],
      mental: ["Deeply grounding, reduces morning lethargy", "Synchronizes rhythm of breath and body action", "Boosts cognitive focus and clarity"],
      medical: ["Stimulates cardiovascular efficiency", "Activates nervous system response", "Improves endocrine gland secretions", "Boosts digestive flora movement"]
    },
    instructions: [
      "Pranamasana (Prayer Pose): Stand at the edge of your mat, bring palms together at your chest.",
      "Hasta Uttanasana (Raised Arms Pose): Inhale, lift arms up and stretch backwards mildly from hips.",
      "Hasta Padasana (Hand to Foot Pose): Exhale, bend forward from hips, touch floor alongside feet.",
      "Ashwa Sanchalanasana (Equestrian Pose): Inhale, push right leg far back, drop right knee, look upwards.",
      "Dandasana (Plank Pose): Hold breath, bring left leg back beside right, hold straight body line.",
      "Ashtanga Namaskara (Eight-Limbed Salute): Exhale, lower knees, chest, and chin to mat.",
      "Bhujangasana (Cobra Pose): Inhale, slide forward, lift chest up, keep elbows close and shoulders soft.",
      "Parvatasana (Mountain Pose / Downward Dog): Exhale, lift hips up, push heels to mat, drop head.",
      "Ashwa Sanchalanasana: Inhale, bring right foot forward between hands, drop left knee, look up.",
      "Hasta Padasana: Exhale, bring left foot forward next to right, bend down to toes.",
      "Hasta Uttanasana: Inhale, raise arms up, stretch backwards.",
      "Pranamasana: Exhale, return to standing with hands in prayer position."
    ],
    breathing: {
      inhale: "Inhale during backward bends (Steps 2, 4, 7, 9)",
      hold: "Hold breath during Plank (Step 5)",
      exhale: "Exhale during forward bends and lowerings (Steps 3, 6, 8, 10, 12)"
    },
    commonMistakes: [
      "Bending knees excessively during forward fold Hasta Padasana without keeping the back neutral.",
      "Locking elbows completely or lifting shoulders up to the ears in Cobra Pose.",
      "Allowing hips to sag too low or hump too high in Plank Pose (Dandasana)."
    ],
    precautions: [
      "Avoid if suffering from severe hernia, high blood pressure, or acute disc slips.",
      "Refrain during late trimesters of pregnancy.",
      "Avoid during unresolved spinal injuries or wrist fractures."
    ],
    scientificEvidence: {
      summary: "Clinical research shows that practicing Surya Namaskar regularly acts as an aerobic metabolic stimulant, improving VO2 Max, decreasing insulin resistance, and increasing parasympathetic tone.",
      citations: [
        "Sinha, B. et al. (2011). 'Cardiorespiratory and metabolic responses during Surya Namaskar.' Indian Journal of Physiology and Pharmacology.",
        "Bhavanani, A. B. et al. (2012). 'Immediate cardiovascular effects of different rounds of Sun Salutations.' International Journal of Yoga."
      ]
    },
    relatedAsanas: ["bhujangasana", "tadasana", "vrikshasana"],
    img: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&q=80&w=600",
    caloriesPerMin: 8.5
  },
  {
    id: "tadasana",
    name: "Tadasana",
    sanskritName: "ताड़ासन",
    englishName: "Mountain Pose",
    difficulty: "Beginner",
    duration: "1 - 3 minutes",
    category: "Beginner Yoga",
    benefits: {
      physical: ["Improves body posture and muscular alignment", "Strengthens thighs, knees, and ankles", "Firms abdomen and gluteal muscles"],
      mental: ["Establishes mental poise and physical equilibrium", "Decreases nervous agitation", "Improves inner body awareness (proprioception)"],
      medical: ["Maintains intervertebral spacing and decompresses spine", "Regulates respiratory diaphragmatic expansion", "Assists as baseline alignment stabilizer for vestibular issues"]
    },
    instructions: [
      "Stand straight with feet slightly apart or big toes touching. Let arms hang naturally beside torso.",
      "Distribute body weight evenly across both feet—from heels to toes.",
      "Inhale, engage your thigh muscles, lift knees up and tuck tailbone slightly.",
      "Interlace fingers, rotate palms outwards, and inhale to raise hands above head.",
      "Stretch your entire body upwards, lifting heels to stand on tiptoes if balance permits.",
      "Keep shoulders soft, shoulder blades rolling down, head centered with chin parallel to floor.",
      "Hold for 5-10 deep breaths, then exhale to gently lower heels and arms."
    ],
    breathing: {
      inhale: "Inhale while lifting arms up and rising onto toes",
      exhale: "Exhale when releasing posture, lowering heels and arms safely"
    },
    commonMistakes: [
      "Locking the knees backwards completely, which increases hyperextension stress.",
      "Tensing shoulders up into the neck, blocking chest ventilation.",
      "Arching the lower back excessively instead of engaging core abdominals."
    ],
    precautions: [
      "Avoid standing raised on tiptoes if experiencing severe headaches or insomnia.",
      "Caution during active low blood pressure spells or vertigo."
    ],
    scientificEvidence: {
      summary: "Biomechanics studies indicate that Tadasana serves to recalibrate normal weight-bearing pathways on spinal joints, stabilizing the foot arch index and correcting moderate postural imbalances.",
      citations: [
        "Madanmohan et al. (2008). 'Effect of yoga training on postural balance.' Journal of Alternative and Complementary Medicine.",
        "Grabara, M. et al. (2015). 'Effects of hatha yoga on spinal postures of young adults.' Journal of Physical Therapy Science."
      ]
    },
    relatedAsanas: ["vrikshasana", "trikonasana"],
    img: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=600",
    caloriesPerMin: 2.2
  },
  {
    id: "bhujangasana",
    name: "Bhujangasana",
    sanskritName: "भुजंगासन",
    englishName: "Cobra Pose",
    difficulty: "Beginner",
    duration: "1 - 3 minutes",
    category: "Back Pain Relief Yoga",
    benefits: {
      physical: ["Strengthens the spinal column extensor muscles", "Stretches chest, lungs, shoulders, and anterior abdominal wall", "Firms posterior thighs and buttocks"],
      mental: ["Relieves general anxiety, stress and emotional tension", "Elevates spirits and battles fatigue", "Increases chest space, easing breathing restrictions"],
      medical: ["Beneficial for lower back aches by improving lumbar lordosis", "Invigorates kidney pathways and outer adrenal tissues", "Enhances respiratory volume in asthmatic symptoms"]
    },
    instructions: [
      "Lie flat on your stomach with your chin resting on the mat, feet together, soles pointing up.",
      "Place palms flat on the mat under your shoulders, fingers pointing forward, elbows tucked close to torso.",
      "Inhale deeply, press your pubic bone firmly into the floor.",
      "Slowly lift head, neck, and chest off the floor. Use back muscle force first, pressing hands minimally.",
      "Keep your navel close to the floor, pelvis fully grounded, and elbows slightly bent.",
      "Roll shoulders back and down away from ears, opening the heart space.",
      "Look gently forward or upwards, maintaining steady breathing for 15-30 seconds. Exhale and lower back down safely."
    ],
    breathing: {
      inhale: "Inhale while arching and lifting the chest upwards",
      exhale: "Exhale while lowering the chest and forehead back down to the ground"
    },
    commonMistakes: [
      "Overstretching the spine by forcing arms completely straight, shifting strain into the lumbar joints.",
      "Lifting shoulders up towards the ears, which pinches cervical nerve spaces.",
      "Allowing knees and feet to splay wide apart, compressing lower sacroiliac joints."
    ],
    precautions: [
      "Avoid if suffering from active hernia, immediate abdominal surgeries, or severe carpal tunnel.",
      "Do not practice during pregnancy.",
      "Avoid during acute flareup phase of cervical or lumbar disc herniation."
    ],
    scientificEvidence: {
      summary: "Functional MRI scans of practitioners during Cobra Pose show activation of lumbar erector spinae muscles accompanied by decreased intra-discal pressure, helping manage radiculopathy.",
      citations: [
        "Tekur, P. et al. (2012). 'Effect of short-term intensive yoga on chronic low back pain.' Pain Medicine.",
        "Nidhi, K. et al. (2013). 'Effect of yoga on back strength and range of motion.' International Journal of Yoga."
      ]
    },
    relatedAsanas: ["surya-namaskar", "dhanurasana", "vajrasana"],
    img: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&q=80&w=600",
    caloriesPerMin: 4.0
  },
  {
    id: "vajrasana",
    name: "Vajrasana",
    sanskritName: "वज्रासन",
    englishName: "Thunderbolt Pose",
    difficulty: "Beginner",
    duration: "5 - 15 minutes",
    category: "Kids Yoga",
    benefits: {
      physical: ["Alleviates joint stiffness in knees, ankles, and thighs", "Stretches quadriceps and ankle extensors", "Enforces perfect static upright spinal posture"],
      mental: ["Deeply relaxing, promotes high mindfulness during static spells", "Calms hyperactive thoughts", "Ideal posture for meditative concentration"],
      medical: ["Redirects blood circulation from thighs to the visceral stomach organs", "Significantly increases digestive fire (Agni), relieving hyperacidity, gas, and indigestion", "Alleviates sciatica cramps"]
    },
    instructions: [
      "Kneel on the mat, bring big toes to touch, and separate your heels to form a comfortable cup.",
      "Slowly lower your buttocks into the space between your heels, sitting back securely.",
      "Place palms resting on your knees, fingers pointing forward or inwards.",
      "Arrive at an upright spine—align ears, shoulders, and hips in a single vertical path.",
      "Close your eyes, relax your facial muscles, jaw, and shoulders.",
      "Breathe slowly, deeply, and deliberately. This is the only pose that can safely be practiced immediately after meals."
    ],
    breathing: {
      inhale: "Maintain deep abdominal inhalations, expanding stomach outline",
      hold: "No holds required; focus on progressive rhythm",
      exhale: "Exhale slowly, drawing your navel softly toward spine"
    },
    commonMistakes: [
      "Sitting directly on the heels instead of letting heels sit slightly flared outside the hips.",
      "Permitting the spine to slouch or slump forwards, compressing abdominal ventilation.",
      "Practicing through deep ankle pain without utilizing an under-shin towel block."
    ],
    precautions: [
      "Avoid if experiencing severe knee ligament injuries, joint effusions, or acute gout.",
      "Caution during active severe osteoarthritic knee pains."
    ],
    scientificEvidence: {
      summary: "Biomedical indices show that sitting in Vajrasana alters the pelvic pelvic blood flow quotient, increasing splanchnic arterial perfusion, which optimizes gastric enzyme secretion and digestion.",
      citations: [
        "Sarang, S. P. et al. (2006). 'Splanchnic blood flow during vajrasana posture.' Journal of Gastrointestinal Motility.",
        "Bera, T. K. et al. (2001). 'Effect of yoga training on digestive systems in middle aged subjects.' Yoga Mimamsa."
      ]
    },
    relatedAsanas: ["padmasana", "bhujangasana"],
    img: "https://images.unsplash.com/photo-1599447421416-3414500d18a5?auto=format&fit=crop&q=80&w=600",
    caloriesPerMin: 1.8
  },
  {
    id: "padmasana",
    name: "Padmasana",
    sanskritName: "पद्मासन",
    englishName: "Lotus Pose",
    difficulty: "Advanced",
    duration: "5 - 30 minutes",
    category: "Yoga for Stress & Anxiety",
    benefits: {
      physical: ["Opens hip joint ligaments and stretches deep adductor complexes", "Strengthens upper back, neck, and abdominal support muscles", "Improves posture alignment during long sessions"],
      mental: ["Induces deeply quiet brain wave transitions (increased Alpha waves)", "Fosters meditation and continuous inward reflection", "Alleviates persistent stress indices"],
      medical: ["Stabilizes pelvic hormonal axes", "Decreases blood pressure levels by calming the sympathetic network", "Relieves menstrual aches and controls metabolic stability"]
    },
    instructions: [
      "Sit on the mat with legs stretched straight forward in Dandasana.",
      "Carefully bend the right knee, use hands to place the right foot onto the left thigh, heel close to hip joint crease, sole facing upwards.",
      "Now carefully bend the left knee. Gently grasp the left foot and slide it up over the folded right leg, placing it onto the right thigh crease.",
      "Secure both knees touching the floor comfortably. Sit completely tall with tailbone neutral.",
      "Rest hands on knees in Jnana Mudra (index finger and thumb tips touching, other fingers extended).",
      "Close your eyes, soften the throat, and observe continuous, calm breaths."
    ],
    breathing: {
      inhale: "Inhale to raise ribs and elongate column height",
      exhale: "Exhale to relax pelvic joints and sink hips firmly downward"
    },
    commonMistakes: [
      "Forcing knees into Lotus pose before hips are sufficiently open, placing heavy rotational strain on knee ligaments.",
      "Rounding the lumbar spine, which collapses chest capacity and restricts diaphragm movement."
    ],
    precautions: [
      "Strictly avoid if suffering from severe knee arthritis, cartilage damage, or ankle weakness.",
      "Contraindicated during acute hamstring tears."
    ],
    scientificEvidence: {
      summary: "Electroencephalogram (EEG) research of meditators in Padmasana shows a significant surge in slow alpha and theta wave activities, indicative of heightened executive attention and autonomic nervous relaxation.",
      citations: [
        "Arambula, P. et al. (2001). 'Physiological correlates of meditation in Lotus Pose.' Biological Psychology.",
        "Telles, S. et al. (2013). 'Autonomic and respiratory changes during Hatha Yoga holding poses.' Journal of Clinical Medicine Research."
      ]
    },
    relatedAsanas: ["vajrasana", "vrikshasana"],
    img: "https://images.unsplash.com/photo-1512438248247-f0f2a5a8b7f0?auto=format&fit=crop&q=80&w=600",
    caloriesPerMin: 1.5
  },
  {
    id: "trikonasana",
    name: "Trikonasana",
    sanskritName: "त्रिकोणासन",
    englishName: "Triangle Pose",
    difficulty: "Beginner",
    duration: "1 - 3 minutes (both sides)",
    category: "Yoga for Diabetes",
    benefits: {
      physical: ["Stretches thighs, calves, hamstrings, knee joints, and hips", "Fully elongates lateral torso, arms, and surrounding rib muscles", "Chest and shoulder muscular openings"],
      mental: ["Builds solid foundation, increasing root safety feelings", "Maintains body equilibrium and bilateral mind pathways", "Relieves persistent mental fog"],
      medical: ["Gently twists abdominal organs, improving liver, spleen, and pancreas efficiency", "Assists in controlling insulin secretion ranges", "Relieves persistent constipation and pelvic cramps"]
    },
    instructions: [
      "Stand tall, step feet wide apart—about 3 to 4 feet.",
      "Turn your right foot completely outward to 90 degrees, and slide your left foot slightly inward to 15 degrees.",
      "Inhale, extend arms straight out sideways at shoulder-height, palms facing down.",
      "Exhale and slide your torso to the right side over your right leg, bending from hip joints, not waist.",
      "Lower your right hand to rest on your shin, ankle, or floor outside foot. Raise left arm straight up towards ceiling, fingers active.",
      "Turn head comfortably to gaze at index finger of raised left hand.",
      "Hold for 5 deep breaths. Inhale to lift torso up, turn feet, and repeat on the opposite side."
    ],
    breathing: {
      inhale: "Inhale when opening arms and when returning torso to center upright stance",
      exhale: "Exhale when sliding and hinging sideways into the posture"
    },
    commonMistakes: [
      "Leaning the torso forward, turning Triangle into a forward collapse rather than a lateral plane stretch.",
      "Dropping weight aggressively onto the lower shin/ankle joint rather than engaging abdominal obliques.",
      "Allowing the rear foot heel to lift off the floor, breaking core alignment."
    ],
    precautions: [
      "Avoid if struggling with severe low/high blood pressure or migrainous spells.",
      "Do not rotate head upwards if cervical pain or vertigo is present; look straight forward."
    ],
    scientificEvidence: {
      summary: "Endocrine reviews imply that twisting lateral poses such as Trikonasana stimulate blood flow in the celiac plexus, facilitating optimal glucose uptake in skeletal muscle groups.",
      citations: [
        "Innes, K. E. et al. (2005). 'The influence of yoga on risk profiles for coronary heart disease and Type II Diabetes.' Journal of Society of Integrative Oncology.",
        "Sahay, B. K. et al. (2007). 'Role of yoga in the management of diabetes mellitus.' Journal of Association of Physicians India."
      ]
    },
    relatedAsanas: ["vrikshasana", "tadasana"],
    img: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&q=80&w=600",
    caloriesPerMin: 5.5
  },
  {
    id: "vrikshasana",
    name: "Vrikshasana",
    sanskritName: "वृक्षासन",
    englishName: "Tree Pose",
    difficulty: "Beginner",
    duration: "1 - 3 minutes (each leg)",
    category: "Senior Citizen Yoga",
    benefits: {
      physical: ["Strengthens joint stability in active ankles, knees, and shin pathways", "Opens tight hip joints and stretches inner adductors", "Tones deep abdominal stabilizers"],
      mental: ["Establishes intense focus, centering racing thoughts", "Increases vestibular inner balance metrics", "Cultivates patience and emotional composure"],
      medical: ["Improves body balance mechanics in seniors, reducing fall risk indices", "Corrects slight pelvic tilts", "Alleviates musculoskeletal pains in hips and calves"]
    },
    instructions: [
      "Stand straight in Tadasana. Focus your gaze on a static point on the wall at eye level.",
      "Shift weight cleanly onto left foot. Bend right knee, gently place sole of right foot high up inside left thigh.",
      "Avoid placing foot directly onto left knee joint (to prevent joint strain); keep it either above or below knee.",
      "Ensure right knee points outwards sideways, opening hip line.",
      "Once balanced, bring palms together into Anjali Mudra (Prayer Pose) in front of chest.",
      "Inhale and raise arms slowly above head, stretching upwards. Hold for 5-10 soft, steady breaths, then release carefully."
    ],
    breathing: {
      inhale: "Inhale when raising hands up into the fully extended position",
      exhale: "Exhale when bringing palms back to chest and safely placing foot down"
    },
    commonMistakes: [
      "Placing the foot sole directly against the side of the knee joint, risking sideways hyperextension.",
      "Letting the hips slide out to the side rather than keeping hips stacked vertically over standing heel.",
      "Bending standing knee instead of keeping standing quad fully active."
    ],
    precautions: [
      "Avoid raising arms if suffering from acute high blood pressure (keep hands at chest).",
      "Avoid if dealing with severe joint instabilities or dizziness."
    ],
    scientificEvidence: {
      summary: "Tree Pose improves lower extremity neuromuscular coordination, increases balance confidence indexes, and decreases lateral sway, which is highly beneficial for the senior demographic.",
      citations: [
        "Hart, C. E. et al. (2008). 'Yoga-based exercise on balance in healthy seniors.' Alternative Therapies in Health and Medicine.",
        "Schmid, A. A. et al. (2012). 'Balance and balance confidence improve after a 12-week yoga intervention for stroke.' PM&R Journal."
      ]
    },
    relatedAsanas: ["tadasana", "trikonasana", "padmasana"],
    img: "https://images.unsplash.com/photo-1552196564-97283c93b371?auto=format&fit=crop&q=80&w=600",
    caloriesPerMin: 3.0
  },
  {
    id: "dhanurasana",
    name: "Dhanurasana",
    sanskritName: "धनुरासन",
    englishName: "Bow Pose",
    difficulty: "Intermediate",
    duration: "30 - 90 seconds",
    category: "Prenatal Yoga",
    benefits: {
      physical: ["Stretches whole front body—chest, throat, abdominals, hip flexors, ankles", "Strengthens entire back muscles and hamstring fibers", "Stimulates shoulder joints mobility"],
      mental: ["Deeply energizing, fights sluggish states and seasonal doldrums", "Instills courage and heart openings", "Relieves mild stress"],
      medical: ["Massages visceral liver, pancreas, and intestinal tubes safely", "Improves thyroid gland balance by extending throat muscles", "Alleviates severe menstrual distress"]
    },
    instructions: [
      "Lie flat on your stomach with feet hip-width apart and arms resting beside torso.",
      "Inhale, bend knees backwards, bringing heels up toward buttocks.",
      "Reach back and grab hold of your ankles safely from the outside. Keep knees no wider than hip-width.",
      "Inhale deeply, press your pubic bone down, and kick legs up and back away from buttocks.",
      "This leverage lifts your thighs and chest off the floor simultaneously.",
      "Roll shoulder blades back, pull shoulders away from ears, open the chest wide.",
      "Breathe through your abdomen. Hold for 15-20 seconds. Return to mat slowly on an exhale."
    ],
    breathing: {
      inhale: "Inhale while kicking legs back and lifting chest up",
      exhale: "Exhale while lowering thighs and chest securely back to floor"
    },
    commonMistakes: [
      "Holding the breath instead of breathing through the belly while in the pose.",
      "Splaying knees out wide apart, which causes harmful compression in the lower back.",
      "Holding toes or feet instead of firmly locking onto stable ankles."
    ],
    precautions: [
      "Avoid if suffering from severe back spinal problems (disc slips), hernia, or colitis.",
      "Contraindicated for pregnant practitioners.",
      "Avoid if experiencing recent neck pain or high blood pressure flares."
    ],
    scientificEvidence: {
      summary: "Endocrine and orthopedic testing indicates that Dhanurasana stretches the deep psoas musculature and regulates abdominal lymphatic flow, optimizing insulin secretion from pancreatic islet cells.",
      citations: [
        "Monro, R. et al. (1992). 'Yoga for common diseases: a clinical guide.' Gaia Books.",
        "Prasad, K. V. et al. (2006). 'Impact of pranayama and asanas on thyroid hormone indices.' Journal of Clinical Biochemistry."
      ]
    },
    relatedAsanas: ["bhujangasana", "surya-namaskar"],
    img: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&q=80&w=600",
    caloriesPerMin: 6.8
  }
];

export const healthConditionsData: HealthCondition[] = [
  {
    id: "diabetes",
    name: "Diabetes",
    icon: "🩸",
    recommendedAsanas: ["trikonasana", "bhujangasana", "vajrasana"],
    benefits: [
      "Assists pancreatic islet cell microcirculation, increasing endocrine efficiency",
      "Increases glucose uptake in peripheral muscle fibers",
      "Lowers chronic cortisol release, reducing insulin resistance"
    ],
    precautions: [
      "Monitor blood glucose levels as intense yoga can cause sudden drops (hypoglycemia)",
      "Avoid deep strains if diabetic retinopathy is present"
    ]
  },
  {
    id: "pcos",
    name: "PCOS",
    icon: "🌸",
    recommendedAsanas: ["dhanurasana", "bhujangasana", "padmasana"],
    benefits: [
      "Regulates blood circulation in pelvic organs and ovarian pathways",
      "Balances LH-FSH hormonal feedback mechanisms",
      "Reduces high stress hormones which exacerbate androgenic issues"
    ],
    precautions: [
      "Avoid highly compressed holds if ovarian cysts are highly inflamed",
      "Engage in restorative holds if experiencing severe pelvic pain"
    ]
  },
  {
    id: "thyroid",
    name: "Thyroid",
    icon: "🦋",
    recommendedAsanas: ["bhujangasana", "dhanurasana", "surya-namaskar"],
    benefits: [
      "Stimulates thyroid glands through deliberate cervical neck extensions",
      "Regulates resting metabolic indices to control weight symptoms",
      "Alleviates fatigue and brain fog associated with Hashimoto's"
    ],
    precautions: [
      "Avoid heavy neck flexions if severe hyperthyroid tremor is actively occurring",
      "Utilize blankets under cervical spine if doing shoulder-stands"
    ]
  },
  {
    id: "obesity",
    name: "Obesity",
    icon: "⚖️",
    recommendedAsanas: ["surya-namaskar", "trikonasana", "dhanurasana"],
    benefits: [
      "Increases daily energy expenditure quotas",
      "Improves core metabolic rate and lipolysis mechanics",
      "Strengthens weight-bearing joints to endure cardiovascular drills"
    ],
    precautions: [
      "Use wall supports or blocks to avoid joint overloading",
      "Transition between poses with a slow pacing to prevent vertical dizzy bouts (orthostatic changes)"
    ]
  },
  {
    id: "anxiety",
    name: "Anxiety",
    icon: "🧠",
    recommendedAsanas: ["padmasana", "tadasana", "vrikshasana"],
    benefits: [
      "Calms autonomic nervous system, moving arousal safely to parasympathetic side",
      "Reduces heart rate and muscle over-activation",
      "Cultivates intense breathing rhythm stabilization"
    ],
    precautions: [
      "Allow eyes to remain slightly open initially to prevent internal panic sensations during silent spell folds",
      "Avoid pushing into long breath-holds if it triggers acute stress reactions"
    ]
  },
  {
    id: "hypertension",
    name: "Hypertension",
    icon: "🫀",
    recommendedAsanas: ["tadasana", "vrikshasana", "vajrasana"],
    benefits: [
      "Lowers systemic vascular resistance (SVR) by stabilizing baroreceptors",
      "Reduces over-active sympathetic drive",
      "Eases chronic high arterial tension over long holds"
    ],
    precautions: [
      "Strictly avoid inverted holds (head lower than waist) as they cause immediate arterial pressure surges",
      "Avoid rapid standing-to-floor transitions"
    ]
  },
  {
    id: "back-pain",
    name: "Back Pain",
    icon: "🦴",
    recommendedAsanas: ["bhujangasana", "tadasana", "vajrasana"],
    benefits: [
      "Decompresses intervertebral lumbar disc segments safely",
      "Erector spinae muscles strengthening",
      "Improves blood flow to tight lower thoracic ligaments"
    ],
    precautions: [
      "Never push through direct stabbing neuropathic pain (sciatica shoots)",
      "Always bend knees slightly during standard forward folds"
    ]
  },
  {
    id: "cervical-pain",
    name: "Cervical Pain",
    icon: "🦒",
    recommendedAsanas: ["bhujangasana", "tadasana"],
    benefits: [
      "Eases chronic neck muscle fatigue and spasms in trapezius",
      "Builds alignment supports in the shoulder girdle",
      "Restores normal physiological cervical posture curves"
    ],
    precautions: [
      "Do not look completely vertically upward in Cobra Pose; keep chin tucked",
      "Avoid any head contact weight loadings"
    ]
  }
];

export const instructorsData: Instructor[] = [
  {
    id: "teacher-1",
    name: "Acharya Ramendra Prasad",
    experience: "18+ Years",
    specialization: "Hatha Yoga & Sanskrit Posture Mechanics",
    rating: 4.9,
    img: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&q=80&w=200"
  },
  {
    id: "teacher-2",
    name: "Dr. Priyamvada Patil",
    experience: "12 Years",
    specialization: "Therapeutic Yoga & Endocrinological Studies",
    rating: 4.8,
    img: "https://images.unsplash.com/photo-1594824813573-246434de83fb?auto=format&fit=crop&q=80&w=200"
  },
  {
    id: "teacher-3",
    name: "Swami Chinmayanan",
    experience: "25+ Years",
    specialization: "Deep Meditation & Pranayama Breathwork",
    rating: 5.0,
    img: "https://images.unsplash.com/photo-1607990283143-e81e7a2c93ab?auto=format&fit=crop&q=80&w=200"
  }
];

export const scientificArticlesData: ResearchArticle[] = [
  {
    id: "res-1",
    title: "Efficacy of 12-Week Yoga Therapy on Glycemic Indexes",
    citation: "Diabetes Care Journal, vol. 34, pp. 222-228, 2011",
    summary: "A clinical trial of standard yoga holds showed a reduction of HbA1c levels from 8.2% to 7.1% in type 2 diabetic cohorts, showcasing cellular insulin receptivity enhancement.",
    pubmedLink: "https://pubmed.ncbi.nlm.nih.gov/"
  },
  {
    id: "res-2",
    title: "Autonomic Modulation & Hatha Folds on Generalized Anxiety",
    citation: "Journal of Psychiatric Research, vol. 112, pp. 88-94, 2019",
    summary: "Evaluation of parasympathetic tone via HRV (Heart Rate Variability) registers indicated that hold stretching reduces the salivary cortisol levels by nearly 31% after 4 weeks.",
    pubmedLink: "https://pubmed.ncbi.nlm.nih.gov/"
  },
  {
    id: "res-3",
    title: "Yoga Asanas on Lumbar Spondylosis Rehabilitation",
    citation: "Spine Journal Clinical Trials, vol. 45, pp. 544-550, 2020",
    summary: "Radiological and muscular follow-ups confirmed that core postural yoga (especially Cobra and mountain poses) decompresses disc spacing and increases local microcirculation.",
    pubmedLink: "https://pubmed.ncbi.nlm.nih.gov/"
  }
];

export const blogPostsData: BlogPost[] = [
  {
    id: "blog-1",
    title: "Understanding Agni: How Sitting in Vajrasana Activates Digestion",
    category: "Yoga Benefits",
    excerpt: "Traditional texts describe Vajrasana as a diamond bolt that locks energy. Modern thermography shows blood redistribution that optimizes digestion path enzyme activation.",
    date: "June 12, 2026",
    img: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=300"
  },
  {
    id: "blog-2",
    title: "The Ayurvedic Saffron Diet: Pairing Spices with Your Yoga Practice",
    category: "Ayurveda",
    excerpt: "Saffron and earthy cumin balances Pitta Dosha and strengthens Agni. Learn how to design a diet routine to supplement daily flexibility.",
    date: "June 05, 2026",
    img: "https://images.unsplash.com/photo-1512438248247-f0f2a5a8b7f0?auto=format&fit=crop&q=80&w=300"
  },
  {
    id: "blog-3",
    title: "Combating Modern Stress Through Vedic Deep Breathing Patterns",
    category: "Meditation",
    excerpt: "Long inhalations followed by sustained holds stimulate the vagus nerve, signaling the heart to slow down and calming mental loops.",
    date: "May 28, 2026",
    img: "https://images.unsplash.com/photo-1599447421416-3414500d18a5?auto=format&fit=crop&q=80&w=300"
  }
];

export const forumPostsData: ForumPost[] = [
  {
    id: "forum-1",
    author: "Gajanan Holi",
    role: "Sadhaka",
    avatar: "https://images.unsplash.com/photo-1599566150163-29194dcaad36?auto=format&fit=crop&q=80&w=100",
    title: "Successfully held Padmasana for 15 minutes without ankle strain!",
    content: "Utilizing Acharya Ramendra's guidance about rolling the femur bones in the hip sockets before crossing ankles worked perfectly. Lower back tension is gone!",
    category: "Alignment Help",
    likes: 18,
    replies: 4,
    time: "2 hours ago"
  },
  {
    id: "forum-2",
    author: "Yogini Shreya",
    role: "Expert",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=100",
    title: "Tips for lowering blood pressure using dynamic Vrikshasana breathing",
    content: "If your blood pressure is high, do not raise your arms. Keep palms at chest and do long 6-second exhalations to calm your autonomic nerves instantly.",
    category: "Therapy Discussion",
    likes: 31,
    replies: 8,
    time: "1 day ago"
  }
];

export const challengesData: Challenge[] = [
  {
    id: "chal-1",
    title: "7 Day Yoga Challenge",
    duration: "7 Days",
    description: "Rejuvenate your daily flexibility with fundamental breathing and dynamic stretching.",
    tasks: ["Day 1: 5m Tadasana & Breathwork", "Day 2: 3 rounds Surya Namaskar", "Day 3: Core holding with Cobra", "Day 4: Posture correction with Tree Pose", "Day 5: Grounding with Lotus breathing", "Day 6: Deep spine folds", "Day 7: Full Suryas and Mindful silence"]
  },
  {
    id: "chal-2",
    title: "21 Day Flexibility Challenge",
    duration: "21 Days",
    description: "Expand hip adductors, release tight hamstrings, and lengthen side spinal muscles.",
    tasks: ["Week 1: Focus on pelvic hip-openers", "Week 2: Hamstrings and spinal releases", "Week 3: Advanced holding patterns & Vajrasana holds"]
  },
  {
    id: "chal-3",
    title: "108 Surya Namaskar Challenge",
    duration: "1 Session",
    description: "The ultimate yogic cardiovascular milestone. Build stamina, detox cells, and manifest positive focus.",
    tasks: ["Round 1-12: Warm-up pacing", "Round 13-48: Focused breathing flow", "Round 49-84: Core deep stamina hold", "Round 85-108: Graceful meditative surrender"]
  }
];

export const badgesData: Badge[] = [
  {
    id: "badge-1",
    title: "First Stretch",
    description: "Practiced your first Yogasana holds.",
    icon: "🧘‍♂️",
    unlocked: true
  },
  {
    id: "badge-2",
    title: "Sadhana Streak 3",
    description: "Maintained active trackers for 3 consecutive days.",
    icon: "🔥",
    unlocked: false
  },
  {
    id: "badge-3",
    title: "Mindfulness Master",
    description: "Maintained silent meditative state on timer for 15+ minutes.",
    icon: "🔔",
    unlocked: false
  },
  {
    id: "badge-4",
    title: "Surya Conqueror",
    description: "Unlocked the full Surya Namaskar guidelines.",
    icon: "☀️",
    unlocked: true
  }
];
